import { Box } from "@chakra-ui/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Search from "../components/search";
import Card from "../components/card";

export default function Home() {
  const myStyle = {
    backgroundColor: "orange",
    minHeight: "100vh",
  };
  return (
    <div className={styles.container} style={myStyle}>
      <Head>
        <title>Weather App</title>
        <meta
          name="An app showing weather details"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Search />
      </Box>
    </div>
  );
}